"""initial_ecommerce_schema

Revision ID: 9ae4c021dc7e
Revises: 20260513_0001
Create Date: 2026-05-13 15:44:02.273462
"""

from alembic import op
import sqlalchemy as sa


revision = '9ae4c021dc7e'
down_revision = '20260513_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
